window._CCSettings = {
    platform: "fb-instant-games",
    groupList: ["default", "ui", "wall", "hero", "enemy", "enemyBeat", "enemyAttack", "beat", "attack", "coin", "body", "jian"],
    collisionMatrix: [
        [false],
        [false, false, false, false],
        [false, false, false, true, true, null, true, null, null, null, null, false],
        [false, false, true, false, false, null, null, null, null, false],
        [false, false, true, false, false],
        [false, false, false, false, false, false, null, null, true],
        [false, false, true, false, false, false, false, true],
        [false, false, false, false, false, false, true, false, null, false],
        [false, false, false, false, false, true, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, true],
        [false, false, false, false, false, false, false, false, false, true, false],
        [false, false, false, false, false, false, false, false, false, false, false, true],
        [false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
        [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
    ],
    hasResourcesBundle: true,
    hasStartSceneBundle: false,
    remoteBundles: [],
    subpackages: [],
    launchScene: "db://assets/FrameWork/View/Logo/LoadScene.fire",
    orientation: "landscape",
    jsList: []
};