text = {
    en: {
        textCongratulations: 'Congratulations\nyou finished\nall levels',
        youwin: 'You Win!',
        txtPause: 'Game paused',
        txtgameover: 'Game Over',
        txtlevel: 'Level ',
        txtscore: 'Score',
        txtmoves: 'Moves',
        txttuto1: 'Match 3 or more items\nof the same color to\ngive the heroes energy\nto beat the monster',
        txttuto2: 'You have to reach\nthe objectives before\nyou run out of moves',
        txtMoreMoves: 'More Moves ?',
        txtGreat: 'Awesome!',
        txtGoodJob: 'Nice!',
        txtUltraChain: 'Mega Chain',
        txtAddCoins: 'Add more diamonds!',
        txtNoCoins: 'Not enough diamonds\nAdd More!',
        txtNoEnoughCoins: 'Not enough diamonds',
        txtWatched: 'Hope you enjoyed it!\nThanks for watching!',
        txtWatch: 'Watch',
        txtClaim: 'Claim',
        txtGet: 'You\'ve got',
        txtFree: 'Free',
        txtNoVideos: 'You watched all videos\nfor now, come back\nlater to watch more',
        txtType: 'item ',
        txtAbility: 'ability ',
        txtAttack: 'Attack: ',
        txtComplete: 'Complete',
        txtNoKeys: 'No keys !',
        txtTutoUnlock: 'Use the keys to\nunlock the boxes and get\ndiamonds and\nnew Candy Friends',
        txtTutoUpgrade: 'You can upgrade\nthe candy friends from\ntheir nest. the upgrades\nwill be vital to win later'
    },
    es: {
        textCongratulations: 'Enhorabuena, \nhas terminado\ntodos los niveles',
        youwin: 'Has ganado',
        txtPause: 'Juego en pausa',
        txtgameover: 'Fin del juego',
        txtlevel: 'Nivel ',
        txtscore: 'Puntos ',
        txtmoves: 'Jugadas',
        txttuto1: 'Empareja 3 o más\nobjetos del mismo\ncolor para dar energía\na los héroes para\nderrotar al monstruo',
        txttuto2: 'Tienes que alcanzar\nlos objetivos antes\nde quedarte sin jugadas',
        txtMoreMoves: '¿Más jugadas?',
        txtGreat: 'IMPRESIONANTE!',
        txtGoodJob: 'Bien!',
        txtUltraChain: 'Megacadena',
        txtAddCoins: 'Añade más diamantes!',
        txtNoEnoughCoins: 'No tienes\nsuficientes diamantes',
        txtNoCoins: '¿No tienes suficientes\ndiamantes? Añade más!',
        txtWatched: 'Espero hayas disfrutado!\nGracias por verlo!',
        txtWatch: 'Ver',
        txtClaim: 'Reclamar',
        txtGet: 'Consigues',
        txtFree: 'Gratis',
        txtNoVideos: 'Has visto todos\nlos vídeos de momento,\nvuelve más tarde',
        txtType: 'objeto ',
        txtAbility: 'capacidad',
        txtAttack: 'Ataque: ',
        txtComplete: 'Completo',
        txtNoKeys: 'No hay llaves!',
        txtTutoUnlock: 'Utilice las llaves\npara abrir las cajas y\nobtener los diamantes\ny las nuevas\ncaramelo Amigos',
        txtTutoUpgrade: 'Puedes mejorar\nlos amigos de dulces de\nsu nido. las mejoras\nserán vitales\npara ganar más tarde'
    },

    de: {
        textCongratulations: 'Gratulation,\nDu hast alle\nLevel geschafft',
        youwin: 'Gewonnen!',
        txtPause: 'Pause',
        txtgameover: 'Game Over',
        txtlevel: 'Level ',
        txtscore: 'Punktzahl',
        txtmoves: 'Züge',
        txttuto1: 'Kombiniere 3 oder mehr\ngleichfarbige Süßigkeiten,\num den Helden Energie zu geben,\nund das Monster zu\nbesiegen!',
        txttuto2: 'Du musst die Ziele\nerreichen, bevor Du\nkeine Züge mehr\nübrig hast!',
        txtMoreMoves: 'Mehr Züge?',
        txtGreat: 'Super!',
        txtGoodJob: 'Gut!',
        txtUltraChain: 'Mega-Kette!',
        txtAddCoins: 'Diamanten hinzufügen!',
        txtNoCoins: 'Nicht genug Diamanten?\nMehr hinzufügen',
        txtNoEnoughCoins: 'Nicht genug Diamanten',
        txtWatched: 'Hat es Dir gefallen?\nDanke fürs Zuschauen!',
        txtWatch: 'Ansehen',
        txtClaim: 'Abholen',
        txtGet: 'Du hast',
        txtFree: 'Kostenlos',
        txtNoVideos: 'Du hast bereits alle\nVideos gesehen,\nversuch es später\nnoch einmal!',
        txtType: 'Objekt ',
        txtAbility: 'Fähigkeit ',
        txtAttack: 'Angriff: ',
        txtComplete: 'komplett',
        txtNoKeys: 'keine Schlüssel!',
        txtTutoUnlock: 'Verwenden Sie die\nTasten, um die Felder\nfreizuschalten und\nDiamanten und neue\nSüßigkeiten zu erhalten',
        txtTutoUpgrade: 'Sie können candy\nFreunde aus ihrem Nest\nzu aktualisieren. Die\nUpgrades werden wichtig\nfür später gewinnen'
    },

    it: {
        textCongratulations: 'Congratulazioni,\nhai completato\ntutti i livelli!',
        youwin: 'Hai vinto',
        txtPause: 'Gioco in pausa',
        txtgameover: 'Game Over',
        txtlevel: 'Livello ',
        txtscore: 'Punteggio',
        txtmoves: 'Mosse',
        txttuto1: 'Abbina 3 o più oggetti\ndello stesso colore\nper dare agli eroi\nenergia necessaria\na battere il mostro',
        txttuto2: 'Devi raggiungere gli\nobiettivi prima di\nterminare le mosse',
        txtMoreMoves: 'Altre mosse?',
        txtGreat: 'Fantastico!',
        txtGoodJob: 'Buono!',
        txtUltraChain: 'Mega-catena',
        txtAddCoins: 'Aggiungi altri diamanti',
        txtNoCoins: 'Non hai abbastanza\ndiamanti? Aggiungi altri!',
        txtNoEnoughCoins: 'Non abbastanza diamanti',
        txtWatched: 'Speriamo ti sia piaciuto!\nGrazie per aver guardato!',
        txtWatch: 'Guarda',
        txtClaim: 'Richiedi',
        txtGet: 'Ottieni',
        txtFree: 'Gratis',
        txtNoVideos: 'Per ora hai visto tutti\ni video, torna più\ntardi o guardane ancora',
        txtType: 'oggetto',
        txtAbility: 'abilità',
        txtAttack: 'Attacco: ',
        txtComplete: 'Completa',
        txtNoKeys: 'Nessuna chiave !',
        txtTutoUnlock: 'Usa le chiavi per\nsbloccare le scatole\ne ottenere diamanti\ne nuove Candy Amici',
        txtTutoUpgrade: 'Potete aggiornare gli\namici caramelle dal loro\nnido. gli aggiornamenti\nsaranno vitali\nper vincere più tardi'
    },

    fr: {
        textCongratulations: 'Félicitations,\nvous avez termié\ntous les niveaux',
        youwin: 'Victoire',
        txtPause: 'Jeu en pause',
        txtgameover: 'Jeu terminé',
        txtlevel: 'Niveau ',
        txtscore: 'Score',
        txtmoves: 'Coups',
        txttuto1: 'Regroupez 3 elements\nou plus de la même\ncouleur pour donner\naux héros l’énergie\npour battre le monstre',
        txttuto2: 'Vous devez atteindre\nles objectifs avant que\nvous manquiez de coups',
        txtMoreMoves: 'Plus de coups ?',
        txtGreat: 'Magnifique!',
        txtGoodJob: 'Joli!',
        txtUltraChain: 'Chaîne méga',
        txtAddCoins: 'Ajoutez plus de diamants',
        txtNoCoins: 'Pas assez de diamants ?\nAjoutez-en plus',
        txtNoEnoughCoins: 'Pas assez de diamants',
        txtWatched: 'Nous espérons que vous\nl\'avez appréciée !\nMerci d\'avoir suivi',
        txtWatch: 'Regarder',
        txtClaim: 'Réclamer',
        txtGet: 'Vous avez',
        txtFree: 'Gratuit',
        txtNoVideos: 'Vous avez regardé toutes\nles vidéos pour\nle moment, revenez\nplus tard pour d\'autres',
        txtType: 'objet ',
        txtAbility: 'capacité ',
        txtAttack: 'Attaque: ',
        txtComplete: 'Complet',
        txtNoKeys: 'Pas de clé!',
        txtTutoUnlock: 'Utilisez les clés\npour déverrouiller\nles boîtes et obtenir\ndes diamants et de\nnouvels Amis Bonbons',
        txtTutoUpgrade: 'Vous pouvez améliorer\nles amis de bonbons de\nleur nid. l\'amélioration\nsera indispensable\npour gagner plus tard'
    },

    pt: {
        textCongratulations: 'Parabéns,\nconcluiu todos\nos níveis.',
        youwin: 'Ganhou',
        txtPause: 'Jogo em pausa',
        txtgameover: 'Jogo terminado',
        txtlevel: 'Nível ',
        txtscore: 'Pontos',
        txtmoves: 'Jogadas',
        txttuto1: 'Combine 3 ou\nmais objetos da\nmesma cor para dar\naos heróis energia para\nvencerem o monstro',
        txttuto2: 'Tem de alcançar os\nobjetivos antes de\nse lhe acabarem\nas jogadas',
        txtMoreMoves: 'Mais Jogadas?',
        txtGreat: 'FANTÁSTICO!',
        txtGoodJob: 'Bom!',
        txtUltraChain: 'Mega Corrente',
        txtAddCoins: 'Adicionar mais diamantes',
        txtNoCoins: 'Sem diamantes\nsuficientes? Adicione mais',
        txtNoEnoughCoins: 'Sem diamantes suficientes',
        txtWatched: 'Espero que tenham\ngostado! Obrigado vendo!',
        txtWatch: 'Ver',
        txtClaim: 'Reclamar',
        txtGet: 'Obteve',
        txtFree: 'Grátis',
        txtNoVideos: 'Por agora, assistiu\na todos os vídeos,\nvolte mais tarde\npara assistir a mais',
        txtType: 'objeto ',
        txtAbility: 'capacidade',
        txtAttack: 'Ataque: ',
        txtComplete: 'Completo',
        txtNoKeys: 'Sem chaves!',
        txtTutoUnlock: 'Utilize as chaves\npara destravar as\ncaixas e obter\ndiamantes e\nnovos doces Amigos',
        txtTutoUpgrade: 'Você pode atualizar os\namigos doces de seu\nninho. as atualizações\nserão vitais para\nganhar mais tarde'
    },

    tr: {
        textCongratulations: 'Tebrikler\ntüm seviyeleri\nbitirdiniz',
        youwin: 'kazandınız',
        txtPause: 'Oyun durduruldu',
        txtgameover: 'Oyun Bitti',
        txtlevel: 'Seviye ',
        txtscore: 'Skor',
        txtmoves: 'Hamle',
        txttuto1: 'Canavarı yenmesi için\nkahramana enerji\nvermek için aynı renkteki\n3 veya daha fazla\nparçayı eşleştirin',
        txttuto2: 'Hamlelerin tükenmeden\nhedeflere ulaştınız',
        txtMoreMoves: 'Daha fazla hamle?',
        txtGreat: 'FEVKALADE!',
        txtGoodJob: 'GÜZEL!',
        txtUltraChain: 'Büyük Zincir',
        txtAddCoins: 'Daha fazla elmas ekle !',
        txtNoCoins: 'Yeterli elmas mı yok?\nDaha Fazla Ekle!',
        txtNoEnoughCoins: 'Yeterli elmas yok',
        txtWatched: 'Umarız beğenmişsindir!\nİzlediğin için teşekkürler!',
        txtWatch: 'İzle',
        txtClaim: 'Talep et',
        txtGet: 'Kazandınız',
        txtFree: 'Ücretsiz',
        txtNoVideos: 'Şimdilik tüm videoları\nizledin, daha sonra\ngel ve daha\nfazlasını izle',
        txtType: 'parça ',
        txtAbility: 'beceri',
        txtAttack: 'Saldır: ',
        txtComplete: 'Tamamla',
        txtNoKeys: 'Anahtarlar Yok!',
        txtTutoUnlock: 'Kutuları açmak ve\nelmas ve yeni Candy\nArkadaşlar almak\niçin tuşlarını kullanın',
        txtTutoUpgrade: 'Onların yuva şeker\narkadaşlarını\nyükseltebilirsiniz.\nyükseltmeleri sonra\nkazanmak için hayati olacak'
    },

    ru: {
        textCongratulations: 'Поздравляем!\nВы прошли\nвсе уровни',
        youwin: 'вы выиграли',
        txtPause: 'пауза',
        txtgameover: 'Игра окончена',
        txtlevel: 'Уровень ',
        txtscore: 'Счет',
        txtmoves: 'Ходы',
        txttuto1: 'Найдите 3 и более\nпредмета одинакового цвета,\nчтобы дать героям\nэнергии для победы\nнад монстром',
        txttuto2: 'Вам нужно достичь\nцелей, до того как\nвы останетесь без ходов',
        txtMoreMoves: 'Больше ходов?',
        txtGreat: 'ПОТРЯСАЮЩЕ!',
        txtGoodJob: 'МИЛО!',
        txtUltraChain: 'Мегацепочка',
        txtAddCoins: 'Добавьте больше\nбриллиантов!',
        txtNoCoins: 'Недостаточно бриллиантов?\nДобавьте еще!',
        txtNoEnoughCoins: 'Недостаточно бриллиантов',
        txtWatched: 'Надеюсь вам понравилось!\nСпасибо за просмотр!',
        txtWatch: 'смотреть',
        txtClaim: 'Требовать',
        txtGet: 'У вас',
        txtFree: 'Бесплатный',
        txtNoVideos: 'Вы посмотрели все доступные\nна данный момент\nвидео, возвращайтесь\nчуть позже,\nчтобы посмотреть еще',
        txtType: 'предмет',
        txtAbility: 'способность',
        txtAttack: 'Атаковать: ',
        txtComplete: 'Завершить',
        txtNoKeys: 'Нет ключей!',
        txtTutoUnlock: 'Используйте ключи,\nчтобы открыть ящики\nи получить алмазы\nи новые конфеты Друзья',
        txtTutoUpgrade: 'Вы можете обновить\nконфеты друзей из\nсвоего гнезда. Модернизация\nбудет иметь жизненно\nважное значение, чтобы\nвыиграть позже'
    },

    th: {
        textCongratulations: 'ขอแสดงความยินดี\nที่คุณเสร็จสิ้นทุ\nกระดับ',
        youwin: 'คุณชนะ',
        txtPause: 'พักเกมชั่วคราว',
        txtgameover: 'เกมมากกว่า',
        txtlevel: 'ด่าน ',
        txtscore: 'คะแนน',
        txtmoves: 'เคลื่อนย้าย',
        txttuto1: 'ตรง 3 หรือรายการอื่น ๆ\nที่มีสีเดียวกันเพื่อให้วีร\nบุรุษพลังงานที่จะเอา\nชนะมอนสเตอร์',
        txttuto2: 'คุณจะต้องบรรลุวัต\nถุประสงค์ก่อนที่จะหมดก\nารเคลื่อนไหว',
        txtMoreMoves: 'เคลื่อนย้ายเพิ่มเติม ?',
        txtGreat: 'เยี่ยม ',
        txtGoodJob: 'ทำได้ดีมาก ',
        txtUltraChain: 'การโยงแบบพิเศษ',
        txtAddCoins: 'เพชรเพิ่มมากขึ้น!',
        txtNoCoins: 'เพชรไม่เพียงพอหรือไม่\nเพิ่มมากขึ้น!',
        txtNoEnoughCoins: 'เพชรไม่พอ',
        txtWatched: 'คุณมีช่วงเวลาที่ดี\nขอบคุณสำหรับการชม',
        txtWatch: 'ชม',
        txtClaim: 'ขอรับ',
        txtGet: 'คุณได้รับ',
        txtFree: 'ฟรี',
        txtNoVideos: 'คุณดูวิดีโอทั้ง\nหมดตอนนี้โป\nรดกลับมาใหม่',
        txtType: 'ชิ้น ',
        txtAbility: 'ความสามารถ',
        txtAttack: 'โจมตี: ',
        txtComplete: 'สมบูรณ์',
        txtNoKeys: 'ไม่มีปุ่ม !',
        txtTutoUnlock: 'ใช้ปุ่มเพื่อปลดล็อคกล่\nองและได้รับเพชรและ\nเพื่อน ๆ แคนดี้ใหม่',
        txtTutoUpgrade: 'คุณสามารถอัพเกรดเ\nพื่อนลูกอมจากรังของพวกเขา\nการอัพเกรดจะเป็นสิ่งสำคัญ\nที่จะชนะในภายหลัง'
    },

    nl: {
        textCongratulations: 'Gefeliciteerd,\nje hebt alle\nniveaus gehaald.',
        youwin: 'Je wint!',
        txtPause: 'Game paused',
        txtgameover: 'Game voorbij',
        txtlevel: 'Level ',
        txtscore: 'Score',
        txtmoves: 'Beurten',
        txttuto1: 'Match 3 of meer items\nvan dezelfde kleur\nom de helden de energie\nte geven om het\nmonster te verslaan',
        txttuto2: 'Je moet de\ndoelstellingen\nhalen voordat je\ngeen beurten meer hebt',
        txtMoreMoves: 'Meer beurten?',
        txtGreat: 'Fantastisch!',
        txtGoodJob: 'Mooi!',
        txtUltraChain: 'Megaketting',
        txtAddCoins: 'Meer Diamanten\ntoevoegen!',
        txtNoCoins: 'Niet genoeg Diamanten?\nMeer toevoegen!',
        txtNoEnoughCoins: 'Niet genoeg Diamanten',
        txtWatched: 'We hopen dat je er plezier\naan hebt beleefd! Bedankt\nvoor het kijken!',
        txtWatch: 'Kijken',
        txtClaim: 'Claim',
        txtGet: 'Je hebt',
        txtFree: 'Gratis',
        txtNoVideos: 'Je hebt nu alle video\'s\nbekeken, kom later\nterug om er meer\nte bekijken',
        txtType: 'item ',
        txtAbility: 'vaardigheid ',
        txtAttack: 'Aanvallen: ',
        txtComplete: 'Afgerond',
        txtNoKeys: 'Geen sleutels!',
        txtTutoUnlock: 'Gebruik de toetsen\nom de dozen te openen\nen krijg diamanten\nen nieuwe Candy Friends',
        txtTutoUpgrade: 'U kunt snoep vrienden\nupgraden van hun nest.\nde upgrades zal\nvan vitaal belang\nom later te winnen'
    },

    pl: {
        textCongratulations: 'Gratulacje\nukończono\nwszystkie\npoziomy',
        youwin: 'wygrałeś',
        txtPause: 'Game paused',
        txtgameover: 'Koniec gry',
        txtlevel: 'Poziom ',
        txtscore: 'Wynik',
        txtmoves: 'Ruchy',
        txttuto1: 'Dopasuj 3, lub więcej\nobiekty tego samego\nkoloru aby dać energię\nbohaterów potrzebną\ndo pokonania potwora',
        txttuto2: 'Musisz osiągnąć cele\nzanim skończą ci\nsię ruchy',
        txtMoreMoves: 'Więcej ruchów?',
        txtGreat: 'Świetnie!',
        txtGoodJob: 'Nieźle!',
        txtUltraChain: 'Mega łańcuch',
        txtAddCoins: 'Dodaj więcej diamentów!',
        txtNoCoins: 'Za mało diamentów?\nDodaj więcej!',
        txtNoEnoughCoins: 'Za mało diamentów',
        txtWatched: 'Mamy nadzieję, że ci\nsię podobało! Dzięki\nza obejrzenie!',
        txtWatch: 'oglądaj',
        txtClaim: 'Odbierz',
        txtGet: 'Masz',
        txtFree: 'Za darmo',
        txtNoVideos: 'Obejrzałeś(-aś) wszystkie\ndostępne filmy,\nwróć później, żeby\nobejrzeć więcej.',
        txtType: 'obiekt ',
        txtAbility: 'zdolność ',
        txtAttack: 'Atak: ',
        txtComplete: 'Zakończone',
        txtNoKeys: 'Brak kluczy!',
        txtTutoUnlock: 'Użyj klawiszy,\naby odblokować pola i\nuzyskać diamenty\ni nowych Cukierki Znajomi',
        txtTutoUpgrade: 'Można uaktualnić\ncukierki przyjaciół\nz ich gniazdo. Uaktualnienia\nbędą niezbędne,\naby wygrać później'
    }
};