var hot = [
    {
        gameId: "1037",
        category: "Action",
        gameName: "Zombie Killers",
        fileName: "ZombieKillers",
        gameLogo: "https://gamefront.91onegame.com/d27f16a8ca6845398ab487d64fb43b52.Webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/73aca62986064c03ac1fc2b3c71f60be.jpg",
        gamePlayNumber: "180185",
        gameDesc: "In future world,an unknown virus ravages the world.The world is taken over by the walking dead surfers around who devour any living thing they catch or hit。Now, Help this soldier avoid getting his brain eaten and save survivors as much as possible.",
        vidUrl: "https://youtube.com/shorts/muVJd2y9tvE"
    },
    {
        gameId: "2493",
        gameName: "Skate Hooligans",
        fileName: "SkateHooligans",
        gameLogo: "https://gamefront.91onegame.com/7bf874d448a34fdcb24628467e4e4c6d.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/6c32594624c542bb91a4db36820e7201.png",
        gamePlayNumber: "100150",
        gameDesc: "In traditional fashion, you’re being chased down and you must dodge obstacles, use power ups, and avoid being hit so you can stay ahead and keep from being caught. This one features leaderboards so you can challenge the scores of your friends along with more acrobatic mechanics than normal. You’ll be jumping on and off of trains, subways, and even power lines. Other than that, it’s a pretty standard offering with a rock solid foundation.",
        vidUrl: "https://youtube.com/shorts/a_1C_9rgweo"
    },
    {
        gameId: "2420",
        gameName: "Piano Tile",
        fileName: "PianoTile",
        gameLogo: "https://gamefront.91onegame.com/44d1681cc5c04c5f8f4ef0bb55760c7f.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/71307fc0551e4db690a933d40fc05be4.png",
        gamePlayNumber: "100031",
        gameDesc: "How fun is it to capture the most precious moments of the year with a wink of rhythm? Let’s MUSIC your soul with all your favorite country tunes!Play your favorite songs and experience them in a whole new way in Piano Tile. Let's explore more to find the rainbow in your mind!",
        vidUrl: "https://youtube.com/shorts/fI17XUst1no"
    },
    {
        gameId: "2376",
        gameName: "Brain Out Funny",
        fileName: "BrainOutFunny",
        gameLogo: "https://gamefront.91onegame.com/4d8c910749cd4a3daabb34ebad5773b8.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/3445210068fd4c4585c4c7b31267de7f.png",
        gamePlayNumber: "100090",
        gameDesc: "Are you ready for the most funny and complicated challenge? Blow your mind with this brain hack game Naughty Quiz: Brain Out Puzzle now!Think outside the box to solve this tricky test. This combination of DOP, displace and brain find game will blow your mind at first sight. Play this brain teaser game with a logic and creative minds. This game will evaluate your IQ and creative thinking. A brand new game experience is waiting for you! ",
        vidUrl: "https://youtube.com/shorts/2sRD9Cqqse8"
    },
    {
        gameId: "2372",
        gameName: "Subway Surfers Web",
        fileName: "SubwaySurfersWeb",
        gameLogo: "https://gamefront.91onegame.com/26676a60a444498f8dd17495d951e5f3.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/3ba0eefe0b2a475cb7601ed2e9183394.png",
        gamePlayNumber: "100271",
        gameDesc: "Subway Runner is a 3D endless running game featuring jumping, dodging, collecting coins, performing stunts and seeing how far you can go.Glide on the subway avoiding any obstacles while trying to collect as many coins as possible. Once you lose your skateboard, you can still run and continue racing. Try to go as far as possible to get the highest score in this fun parkour game.",
        vidUrl: "https://youtu.be/ZtKkjP3xRHo"
    },
    {
        gameId: "2577",
        gameName: "Mob Control",
        fileName: "MobControl",
        gameLogo: "https://gamefront.91onegame.com/0212da5a76da4234a34a49023df09d88.webp",
        gamePlayNumber: "100092",
        gameDesc: "Launch people onto multiplier gates to increase your crowd and capture all the bases! Avoid the red gates and push back the red crowd, trying to ruin your fun! How many people can you gather?",
        vidUrl: "https://youtu.be/CtVCi6ndcIc",
        type: "action",
        rating: "4.3",
      },
      {
        gameId: "1818",
        gameName: "Hill Climber",
        fileName: "HillClimber",
        gameLogo: "https://gamefront.91onegame.com/863f764821cf4149b1d9f1fefe399ec9.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/0e76631556b84b2a8191a8b04580816c.png",
        gamePlayNumber: "100003",
        gameDesc: "\"Hill Climb Racing 2\" is \"Hill Climb Racing\" is also an interesting physics-based driving game. Young aspiring uphill racer. He is about to embark on a journey and will take him on an unprecedented journey. He almost ignored the laws of physics, and he would not rest until he conquered the highest hill! Play the original classic Hill Climb Racing! Race your way uphill in this physics-based driving game, playable offline!Meet Bill, the young aspiring uphill racer. He is about to embark on a journey that takes him to where no ride has ever been before. With little respect to the laws of physics, Bill will not rest until he has conquered the highest hills up on the moon!Face challenges in unique hill climbing environments with a wide variety of cars to choose from. Earn points from daring tricks and collect coins to upgrade your car and travel further distances. Watch out though - Bill's neck is not what it used to be when he was a kid! And his good old gasoline crematorium will easily run out of fuel."
    },
    {
        gameId: "1296",
        gameName: "Charge Now",
        fileName: "ChargeNow",
        gameLogo: "https://gamefront.91onegame.com/fd534c0452a8414daea7ae103e273ac0.webp",
        gamePlayNumber: "114155",
        gameDesc: "Connect all the plugs to a matching socket. But, as in real life, it isn't as easy as it sounds!Hypercasual game with one finger control. Easy to play, hard to master.",
        type: "New",
        rating: "4.5"
      },
      {
        gameId: "1553",
        gameName: "Mr Bullet 3D",
        fileName: "MrBullet3D",
        gameLogo: "https://gamefront.91onegame.com/2de411c7baff437396f2000f5b7c8bc3.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/2b64016cdfa040368befecdb49b4c959.jpg",
        gamePlayNumber: "101101",
        gameDesc: "A spectacular fun action game is coming, full of action, fun and many challenging levels play it now Mr Bullet 3D a new exclusive game  !!!! Looking for a game that can entertain you full of action and lots of fun? this game is for you, in this shooting game you will control the character Mr Bullet and help him to aim and shoot in the right direction try to calculate the angles, rebounds and take care of your ammunition to eliminate the agents in each level, have fun with this spectacular New game from our collection of free games with rewards .",
        type:"new",
        rating:"5.0",
    },
    {
        gameId: "2561",
        gameName: "Brain Quiz",
        fileName: "BrainQuiz",
        gameLogo: "https://gamefront.91onegame.com/2d776ddb45af48a58b861cc33cbb5073.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/58cb6d4c5b6e4b2f805ef0a983dee6c2.png",
        gamePlayNumber: "100783",
        gameDesc: "Brain Quiz - Tricky Test is an addictive free tricky puzzle game with a series of tricky brain teasers.This funny brain game can evaluate your logical think ability, reflexes, accuracy, memory and creativity with different riddles. Moreover, Brain Puzzle can make your brain explode and bring you new brain-pushing experience. You can enjoy yourself with your friends with this addictive brain game.",
        vidUrl: "https://www.youtube.com/watch?v=CtVCi6ndcIc",
        rating: "4.2",
        type: "Puzzle",
      },
    {
        gameId: "2189",
        gameName: "Donut Stack",
        fileName: "DonutStack",
        gameLogo: "https://gamefront.91onegame.com/b166280690c54a069f2f324625dc5053.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/7e6dd5a89f564a0d832eca51976eec03.png",
        gameDesc: "Donut Stack is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Welcome to join Donut Stack! Donut Stack is a fun donut running casual game. Collect and make donuts, experience the process of donut making, and finally present the prepared donuts to the customers. Also, watch out for obstacles on the road, they will take your donuts! Call your friends and family and join the doughnut-making journey! Have fun!",
        vidUrl: "https://youtu.be/guSXoN41WNM",
        type: "action",
        rating: "5.0",
        gamePlayNumber: "241012"
      },
    {
        gameId: "2007",
        gameName: "Om Nom Run",
        fileName: "OmNomRun",
        gameLogo: "https://gamefront.91onegame.com/c3e4c595b0ec48b7b23e6ca3c6b98e78.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/609a97b9ac2f42d889da7a0b843c9100.png",
        gamePlayNumber: "100115",
        gameDesc: "Om Nom: Run is a running game set on the mean streets of Nomville. Complete the set challenges on each level to succeed. There are various power-ups and bonuses to help.",
        vidUrl: "https://youtube.com/shorts/2P2nnIaicVI"
    },
    {
        gameId: "1979",
        gameName: "MineWarfire Land Defense",
        fileName: "MineWarfireLandDefense",
        gameLogo: "https://gamefront.91onegame.com/ffa11c2ae2d245b39c788fda5ad02304.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/0d937d1388de479ea8ca022004fc4b91.png",
        gamePlayNumber: "100032",
        gameDesc: "Play for free and have fun in MineWarfire Land Defense a game of war, action and shooting! Defend your territory from the invasion of creepy minezombies who want to conquer your lands!!!",
        vidUrl: "https://youtu.be/5QsRQBSaIfY"
    },
    {
        gameId: "2408",
        gameName: "Stumble Guys",
        fileName: "StumbleGuys",
        gameLogo: "https://gamefront.91onegame.com/53fb8625240248afa710cd9429e1ca8e.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/534095c44a04472ca3b9d344b46d29d4.png",
        gamePlayNumber: "100464",
        gameDesc: "Stumble Guys is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Stumble Guys is a very hot adventure elimination game. A variety of fun levels await your challenge, and the time has come to test your memory and dexterity! Run, sprint, and slide to overtake your opponents and dodge the obstacles that keep popping up. Can you survive to the end? Invite your friends to join you and kill them all!",
        vidUrl: "https://youtube.com/shorts/_YqWot5ZJOU"
    },
    {
        gameId: "117",
        gameName: "Cut the Rope Time Travel",
        fileName: "CuttheRopeTimeTravel",
        gameLogo: "https://gamefront.91onegame.com/45b5e3f371c74b3d94ccb5ff621a3fb3.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/1a14f86334f34b94a3f8cfee269eed4e.png",
        gameDesc: "Players have to cut the ropes to get the candy to fall into their mouths. The difficulty is to plan to eat the stars as the candy falls.Follow the adventure of Om Nom in the first part of the legendary 'Cut the Rope Time Travel' logic puzzles series. ",
        vidUrl: "https://youtu.be/mKLL0EnHGr4",
        type: "action",
        rating: "4.7",
        gamePlayNumber: "130727"
    },
    {
        gameId: "1098",
        gameName: "Car Rush2",
        fileName: "CarRush2",
        gameLogo: "https://gamefront.91onegame.com/5b5f1e2ae8c145fda99d262f46b1817c.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/99d7436dd8bb4e0b903b9c83c804420e.jpg",
        gamePlayNumber: "287585",
        gameDesc: "Car Rush is a very interesting leisure puzzle game. It's simple, easy and pleasant to play, it will bring you a comfortable experience. You need to control your own car, drive on the road, avoid all kinds of obstacles, and try to survive for a longer time. Can you create a new score in our new 3D relaxing game Car Rush? Have a try!",
        vidUrl: "https://youtu.be/uZdnvxp-A34"
    },
    {
        gameId: "1112",
        gameName: "Bike Rush",
        fileName: "BikeRush",
        gameLogo: "https://gamefront.91onegame.com/e17c82b84e3942d9bffb3ea796d47a66.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/b6032c88d44645369b93a67c3b8c2e8c.jpg",
        gamePlayNumber: "102140",
        gameDesc: "Bike Rush is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Bike Rush is a new driving experience game that can let many players drive a very cool bike. Players will join a united cycling team in the bike rush competition, start a crazy cycling journey, go through all kinds of rugged tracks and participate in all kinds of large-scale high-speed cycling competitions. Enjoy the Bike Rush! ",
        vidUrl: "https://youtu.be/K1M6yTzvm0g",
    },
    {
        gameId: "1473",
        gameName: "Eye Art",
        fileName: "EyeArt",
        gameLogo: "https://gamefront.91onegame.com/4a5a1b05131747cba6679b86106e950e.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/213a67da8c124ce1adba793349f48f96.png",
        gamePlayNumber: "230290",
        gameDesc: "Eye Art is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Eye makeup is very important for every girl. Have you ever dreamed of becoming a professional eye makeup designer? In the Eye Art game, you will play this role and choose suitable eye makeup for customers. You only need to slide the mouse according to the instructions in the game to complete dozens of different eye makeup, each eye makeup has dazzling colors and unique patterns, as your skills continue to improve, more creative eye makeup will be unlocked. ",
        vidUrl: "https://youtu.be/muMkMvJRikQ"
    },
    {
        gameId: "1506",
        category: "Action",
        gameName: "Pet Parkour",
        fileName: "PetParkour",
        gameLogo: "https://gamefront.91onegame.com/3fe75c6485ba4b8daf7c6e44fff7ec24.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/80322f0c560a4627b722c3deba4bdb99.jpg",
        gamePlayNumber: "106351",
        gameDesc: "Come and have fun for free with this amazing endless runner! Chase after the robber who stole your gold and unlock new worlds. Do you have what it takes to run through all the worlds and win? It’s not super easy to be the best, but we believe in you! Start running and racing now. It’s time to go for gold!.",
        vidUrl: 'https://youtu.be/yqw4NI1Gutk'
    },
    {
        gameId: "1899",
        gameName: "Paper Fold",
        fileName: "PaperFold",
        gameLogo: "https://gamefront.91onegame.com/a027c9d44e674f7f887e55c87718d35f.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/ec02cf1d17104a97b9035d27f488e63d.png",
        gamePlayNumber: "222212",
        gameDesc: "Paper Fold is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Paper Fold is a game with Interesting gameplay and easy controls which is made for all players who like origami games! You can click on a corner of the paper to fold it. Folding the paper in the right order can make interesting patterns! You can unlock more backgrounds and patterns in the game. Don't forget to use the hints if you get stuck! Have fun!",
        vidUrl: "https://youtu.be/K3vEwQAR1tE"
    },
    {
        gameId: "2154",
        gameName: "Diy Joystick",
        fileName: "DiyJoystick",
        gameLogo: "https://gamefront.91onegame.com/51cfad5f84aa4b7f8d3718c04e4390bd.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/fcbf4f5b7a1d4213a72f21d491bdc7bd.png",
        gamePlayNumber: "100076",
        gameDesc: "Hey game fans! Ready to join the Console Evolution initiative and design cool DIY joysticks and gamepads for your console games?Use stencil doodles, spray paint, colors, and stickers to create your favorite images on custom joysticks.DIY Joysticks are just as creative as DIY Keyboard, but in this game, you'll design your console joystick and gamepad with spray paint, stencil doodles, cool stickers, and ball dipping! And it's more than that! You can also enjoy cool crafts for all kinds of game controllers and accessories, such as PS4 controllers, controllers, consoles, guns, Atari consoles, headsets, VR kits, Nintendo Switch, etc...Let your imagination run wild! What kind of DIY joystick would you make for console games? Let's wait and see!",
        vidUrl: "https://youtu.be/OQ-3t11HR_w"
    },
    {
        gameId: "1479",
        gameName: "Nail Art",
        fileName: "NailArt",
        gameLogo: "https://gamefront.91onegame.com/b2a3ac94877d4653b856092532f15b3f.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/e9e2810601924c2bb5d6697d2db30ac0.png",
        gamePlayNumber: "116247",
        gameDesc: "Nail Art is an Other game on GaHe.Com. You can play Nail Art in your browser for free. Absolutely amazing fashion nail art salon within the latest pedicure Nail Art! Haven't you always wanted to have the most beautiful realistic nails and the nail fashion design skills of a pro manicurist or pedicurist? There are many hand spa and nail art games with finger makeover options, but not nearly enough nail polish games that offer you a wide variety of gorgeous design patterns and an unlimited number of cute nail polish colors, stickers, and other accessories. Finally, the most beautiful-looking fashion nails are now available in Nail Art!  ",
        vidUrl: "https://youtu.be/gK7eK4ZkKJ8"
    },
    {
        gameId: "1641",
        gameName: "Phone Case DIY",
        fileName: "PhoneCaseDIY",
        gameLogo: "https://gamefront.91onegame.com/40c50e1adbae4bf0831d82fc1f4a71c5.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/e86adcf155bb410796cd6a9d5ff7198f.jpg",
        gamePlayNumber: "100460",
        gameDesc: "Phone Case Diy is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Even a small mobile phone case can be created with the most fashionable patterns. In the Phone Case Diy game, you can use your imagination and creativity to make a fantastic mobile phone case. You can choose to include Various shapes including My Little Pony, rabbit, cactus, ice cream, etc, and then paint beautiful colors and patterns on the phone case to make your phone case shiny, and finally, don't forget to attach ornaments to the phone case and In order to attract the attention of the princesses!",
        vidUrl: "https://youtu.be/L2BY__v4B-Q"
    },
    {
        gameId: "2244",
        gameName: "Home Pipe Water Puzzle",
        fileName: "HomePipeWaterPuzzle",
        gameLogo: "https://gamefront.91onegame.com/c73077746dae463dae9d5b09929bf1f5.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/af5180d289f74253831ccb5e1edf112a.png",
        gamePlayNumber: "100022",
        gameDesc: "Fix the pipes and show your engineering to help those in distress!Nobody likes getting wet - most of your customers certainly don't! Fix the pipes and show your engineering and puzzle-solving skills in a unique way!You will players step into the shoes of a handyman plumber who must solve the damages that his customers are suffering. In this way, you must make the right connections to bring water or other fluids to their homes.",
        vidUrl: "https://youtu.be/WM6BQd7vvto"
    },
    {
        gameId: "1342",
        gameName: "Barbie Artistic Eye Makeup",
        fileName: "BarbieArtisticEyeMakeup",
        gameLogo: "https://gamefront.91onegame.com/e4aa4c82e9734909b2aa8d27273b8b04.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/9a64aeb751514c3db0046a0aad92a62a.png",
        gamePlayNumber: "103244",
        gameDesc: "Barbie Artistic Eye Makeup is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. There is a new beauty shop opened! It's said that the makeup artist here can design any pattern you want. Barbie can't wait to have a beautiful eye makeup. Can you help her? Choose your favorite pattern to start the game!",
        vidUrl: "https://youtu.be/bSaqiiIG_9A"
    },
    {
        gameId: "1120",
        gameName: "Drifty Race",
        fileName: "DriftyRace",
        gameLogo: "https://gamefront.91onegame.com/2d9e5a31acfa49ebb32ee1e632422434.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/7abbb00d205d4c9aa95862c33dab2491.png",
        gamePlayNumber: "100240",
        gameDesc: "Here is a car stunt racing arcade game that is made of 3D game engine. You have a chance to concentrate on the timing of drifting rather than speeding up which is actually automatic. Why not entertain with this game for relax?",
        vidUrl: "https://youtu.be/wwlnIrRhtE8"
    },
    {
        gameId: "2054",
        gameName: "Popsicle Stack",
        fileName: "PopsicleStack",
        gameLogo: "https://gamefront.91onegame.com/e756f1b6adbf4ac4bc0bcf34fa96bf05.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/0c4b48bad9bd41dd826c460e8016e673.png",
        gamePlayNumber: "100120",
        gameDesc: "Popsicle Stack is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. The summer heat is coming, are you ready to get rid of the heat? Come and join Popsicle Stack to make your own ice cream! What flavor do you like? White chocolate or dark chocolate? Or a cool and delicious fruit flavor? Finish it off with a delicious little topping of nuts. Everything is so good! Don't hesitate to join us! Have a great time!",
        vidUrl: "https://youtu.be/FnpKPS2hw7M"
    },
    {
        gameId: "906",
        gameName: "Flip Bottle",
        fileName: "FlipBottle",
        gameLogo: "https://gamefront.91onegame.com/9277e24b783741afa7828ac3ce2f9137.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/76eba88f81a5453fa62bdda4215fbeb0.png",
        gamePlayNumber: "118846",
        gameDesc: "Flip the bottle and make it jump from object to object to reach the final platform.You have to flip a plastic bottle in the exciting arcade game Flip Bottle! Make the bottle jump or even double flip. How? Just tap the screen at the right moment and jump!Explore different rooms, jump on all sorts of objects: shelves, tables, chairs, sofas, and even subwoofers! Train your agility, develop coordination, control the strength and distance of the jump. And most importantly - calculate the distance correctly because it depends on whether you can get to the finish line and win!",
        vidUrl: "https://youtu.be/Qq2oYNh4ymo"
    },
    {
        gameId: "1447",
        gameName: "Stacky Run",
        fileName: "StackyRun",
        gameLogo: "https://gamefront.91onegame.com/5833ae36e0004d999c4307f19da2f045.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/fcfe80789dfe43e0be741dd585405a13.png",
        gamePlayNumber: "102472",
        gameDesc: "Stacky Run is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Stacky Run is a funny arcade running game. It is simple. Pick up the bricks on the island. If you have not enough bricks, you can't through the water. Collect more bricks that you can step on the latest island. There are so many diamonds waiting for you!",
        vidUrl: "https://youtu.be/jcogKGcxZTY"
    },
    {
        gameId: "2205",
        gameName: "Cake Art",
        fileName: "CakeArt",
        gameLogo: "https://gamefront.91onegame.com/4e997531343b4211bbb2bcf667b966ce.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/de3ef3b1efd7416eb6ae297c23ca79a3.png",
        gamePlayNumber: "151112",
        gameDesc: "Cake Art is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Cake Art is a casual art game of delicious cake making. No one can say no to a delicious cake and the process of making it is anticipated and exciting. There are twelve delicious cakes for you to choose from, Paint lovely shapes on the cakes with cream and decorate them with nice decorations to make your cakes more tempting and delicious. Have a great time!",
        vidUrl: "https://youtu.be/R-vZ-gP6wkw",
    },
    {
        gameId: "1282",
        gameName: "Elsa With Ice Cream Car",
        fileName: "ElsaWithIceCreamCar",
        gameLogo: "https://gamefront.91onegame.com/141eceeb17df400cb68e419d1ae07896.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/49da063d13f44477974e3f53176bbec0.png",
        gamePlayNumber: "103160",
        gameDesc: "Elsa With Ice Cream Car is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Elsa has an ice cream car. This day she decides to make some ice cream and go to the park to sell ice cream. But Elsa is not very familiar with the steps of making ice cream. She wants you to make ice cream with her. ",
        vidUrl: "https://youtu.be/I6dxOBGZrTA"
    },
    {
        gameId: "2119",
        gameName: "Sniper Action",
        fileName: "SniperAction",
        gameLogo: "https://gamefront.91onegame.com/9069df40a48d40218785a55300c4d52a.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/3c41663fbee24aa089565cbd33a7c43b.jpg",
        gamePlayNumber: "100208",
        gameDesc: "Traditionally, such popular games have forced us to chase targets and hide in corners to stay safe. As a result, you usually feel stressed and nervous because of the constant risk to the hero's life. Not this time, however, as the sniper game has been modified and improved.",
        vidUrl: "https://youtu.be/KH0QNX3Mpks"
    },
    {
        gameId: "2108",
        gameName: "Build Bridge",
        fileName: "BuildBridge",
        gameLogo: "https://gamefront.91onegame.com/9c02e0d8ada444f7a28b249652991553.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/14410113f5da44b0a444dab419fab559.jpg",
        gamePlayNumber: "100029",
        gameDesc: "Build BridgeDrag to create a path and guide the car to the goal!You can only draw the line once, be careful not to break the car!You can only draw it once, make sure the car bridge you create is strong enough. Safety comes first, make sure your car gets to the finish line safely. (The road that is not smooth enough will cause the car to roll over and break.",
        vidUrl: "https://youtu.be/-rYId4qHoE0"
      },
    {
        gameId: "2034",
        gameName: "Water Sort Puzzle",
        fileName: "WaterSortPuzzle",
        gameLogo: "https://gamefront.91onegame.com/ceab67ab9b83450a9886784d9e00c44d.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/284a77dace374638b71dba0da1db8f64.jpg",
        gamePlayNumber: "100208",
        gameDesc: "If you’d like to train your combinational logic, this water sort puzzle game is just for you! It’s the most relaxing and challenging puzzle game, and it’s not timed.💦Now try to pour the water in different colors and sort the water in the same color into the same bottles. 🧪This water sort puzzle game is quite simple, but it’s very addictive and challenging. The difficulties of levels are increasing. The higher level you play, the more difficult it would be, and the more careful you would be for each move. This is the best way to train your critical thinking.",
        vidUrl: "https://youtu.be/CtVCi6ndcIc"
    },
    {
        gameId: "2093",
        gameName: "Tap On Time",
        fileName: "TapOnTime",
        gameLogo: "https://gamefront.91onegame.com/098bd1214c5a4d6499a09de8864c4874.webp",
        gameDetailsImg: "https://gamedesc.91onegame.com/24f719393bfb4215983caf8210e79025.jpg",
        gamePlayNumber: "100020",
        gameDesc: "Test your reflexes in this fast-paced game. Your mission is to tap the loop at the right moment. Sounds easy, right? Go ahead and try yourself. Play levels or endless mode and climb to the top of leaderboard. Good luck.",
        vidUrl: "https://youtu.be/8EvTIgJTLjY"
    },
{
            "gameId": "2200",
            "gameType": "New,Action",
            "gameName": "Coffee Stack",
            "fileName": "CoffeeStack",
            "gameLogo": "./webp/7657efb38cc34bdebbc97b277d38db91.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/c0a1b38619864140bc6b50f0b93ba2cf.png",
            "gamePlayNumber": "100212",
            "gameDesc": "Start with a coffee cup & Collect coffee cups and stack them in a long queue. Upgrade your line to turn your coffees into delicious drinks, sweet cappuccinos, lattes, and Frappuccino's! Add the beautiful sleeves, put on cute lids, and voila! You have an art piece of coffee cups!\nHowever, not only will we have to save our coffee, but also advance and accumulate more and more cups while dodging precaps, machines that will destroy our cups, and hands that try to snatch them away...\nWatch out for obstacles on the way, some people want to take the coffee without paying for it, but it's not possible!",
            "vidUrl": "https://youtu.be/K18pH8qYij8"
        },
        {
            "gameId": "1438",
            "gameType": "New,Action",
            "gameName": "Shortcut Run",
            "fileName": "ShortcutRun",
            "gameLogo": "./webp/5167a4f4f65f41bd8fd267d782c2367b.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/3e46921cd06c48969f076f24eb8b2beb.png",
            "gamePlayNumber": "101549",
            "gameDesc": "Shortcut Run is a parkour game as well as a new arcade game. In the game, you need to collect wooden blocks on the platform. These wooden blocks allow you to build a road faster than others on the water. The more blocks, the more coins you will get. These coins can be used to exchange for different cartoon character skins. At the same time, running on the water can increase your speed. Are you ready? You will race with others. If you want to win the game, run on the water will speed you up, but it also will cost the bricks. So you need to collect them. ",
            "vidUrl": "https://youtu.be/0ikivybpnJ8"
        },
        {
            "gameId": "2162",
            "gameType": "New,Action",
            "gameName": "Hide Or Seek",
            "fileName": "HideOrSeek",
            "gameLogo": "./webp/054bca1fd5be40fa9590ab569e12dffe.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/4e7c7966dec64dba89a2ad60277c5ab2.png",
            "gamePlayNumber": "100059",
            "gameDesc": "Hide Or Seek is a puzzle action online game for boys for free. In this game, you will start the competition with others in a small maze. When seeking other people, you need to carefully observe some dust and footprints around the character as clues to find others. As a hider, you need to avoid the seeker's vision as much as possible, so you should immediately",
            "vidUrl": "https://youtu.be/Zs0faVac7xE"
        },
        {
            "gameId": "1992",
            "gameType": "New,Action",
            "gameName": "Ninja Legend",
            "fileName": "NinjaLegend",
            "gameLogo": "./webp/0b678b06d2664ab6a5fb1a7333882eeb.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/cdf9ab62b3da44a29487181d62978610.webp",
            "gamePlayNumber": "100008",
            "gameDesc": "Welcome to the ninja world.The position of the enemy in the front varies. Use the weapons in your hand, aim quickly, destroy them and become the strongest hero.",
            "vidUrl": "https://youtu.be/SqRu-GwGXTo"
        },
        {
            "gameId": "2510",
            "gameType": "Puzzle,New",
            "gameName": "Shoes Diy",
            "fileName": "ShoesDiy",
            "gameLogo": "./webp/b372330d7dee4d629c22a6aff6c8f0c7.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/418fabc2e6b3417ab13d3a3224805278.png",
            "gamePlayNumber": "100435",
            "gameDesc": "Become a PRO sneaker artist! Grab your paint brush and design DIY custom sneakers in art games. Show your coloring games skills, paint shoes to create artistic designs in DIY Games. Make Custom designs, place the sneaker art on display and sell them in your sneaker shop!\nFun and addictive design games, work as a sneaker artist, and show your hidden art skills! Start with painting the sneaker just like coloring games and create the perfect design. Do a DIY custom paint job, create unique designs in sneaker art games. Match the design perfectly, or make your own in shoes games!\nMake DIY custom shoe designs using different brushes and color in art games. Next step is to lace up, Choose from dozens of laces in a sneaker shop. Pack your designed sneakers in a box and put them on display in shoes games.",
            "vidUrl": "https://youtube.com/shorts/f_cxUksF5UI"
        },
        {
            "gameId": "2729",
            "gameType": "New,Action",
            "gameName": "Shooter 3D Goblin Attack",
            "fileName": "Shooter3DGoblinAttack",
            "gameLogo": "./webp/24ec162fa6d042208855593dfe7fe25b.webp",
            "gameDetailsImg": "",
            "gamePlayNumber": "100019",
            "gameDesc": "\"Shooter 3D Goblin Attack\" is an exciting first-person shooter where you will fight against evil goblins, ferocious wolves and flying demons. You will go in search of a princess who has been kidnapped by an evil goblin chief.",
            "vidUrl": "https://youtu.be/EWuQ984ur44"
        },
        {
            "gameId": "2562",
            "gameType": "Puzzle,New",
            "gameName": "Rope Rescue Puzzle",
            "fileName": "RopeRescuePuzzle",
            "gameLogo": "./webp/5dae56881b2b4225a79ea12bbcfaa067.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/986d6cf1f93c49e185b3dc23754c67eb.png",
            "gamePlayNumber": "100239",
            "gameDesc": "Join the rescue mission to become the hero with one of the rope games now! A free easy game that gives you unique and engaging puzzles. All you need to do in this easy game is to drag the rope to save them all from the fire?. Very attractive, lots of fun and addictive for everyone?",
            "vidUrl": "https://youtu.be/xzXLlvT0loo"
        },
        {
            "gameId": "2734",
            "gameType": "Puzzle,New",
            "gameName": "Protect My Dog 2",
            "fileName": "ProtectMyDog2",
            "gameLogo": "./webp/9c0edaeb78ad4fbfa361b7ca1a64b5f0.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/20ff0dae9fcf41c881143b9cbfe87c31.png",
            "gamePlayNumber": "100038",
            "gameDesc": "\nProtect My Dog continues with the second part of the game. The evil bees have come out to sting him. The only way you can save the dog is to draw a line to stop those bees. Fighting the Bees will continue for 85 Levels and things will get a little more difficult with each level.",
            "vidUrl": ""
        },
        {
            "gameId": "1691",
            "gameType": "New,Kids,Home",
            "gameName": "Creative Cake Bakery",
            "fileName": "CreativeCakeBakery",
            "gameLogo": "./webp/69515ca2967145299efe4fa4a9e73669.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/98e58344da514ee48b3d34679ba9ed4d.png",
            "gamePlayNumber": "100258",
            "gameDesc": "Creative Cake Bakery is an online Kids game, it's playable on all smartphones or tablets, such as iPhone, iPad, Samsung and other Apple and android system. Cakes are undoubtedly one of the most popular desserts. The method is very simple. You can practice making this kind of cake at home. It looks very beautiful. Today, we are going to make cartoon mermaid and unicorn-shaped cupcakes and decorate them. The product is very complicated. You can choose the colors and decorations you like. You need to make cakes according to the hints and recipes in the game.",
            "vidUrl": "https://youtu.be/xQKGUlO70ak"
        },
        {
            "gameId": "1130",
            "gameType": "New,Action",
            "gameName": "Slap Kings",
            "fileName": "SlapKings",
            "gameLogo": "./webp/c2010aac923741d6880c04644c0bc945.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/c3c8e1f5e2ec46398a232c4cbe2978df.png",
            "gamePlayNumber": "102451",
            "gameDesc": "Slap Kings is a free mobile game where you virtually slap your opponent in the face to earn points and go up levels. You play against the game, rather than other players, and there aren’t any communication features. The game has overtly violent themes.",
            "vidUrl": "https://youtu.be/_75mmY8nFYU"
        },
        {
            "gameId": "2081",
            "gameType": "Puzzle,New",
            "gameName": "Diy Keyboard",
            "fileName": "DiyKeyboard",
            "gameLogo": "./webp/64b7e423677746a89427a8a97aa4332e.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/9052198b35df482696b7d0df814d899e.png",
            "gamePlayNumber": "100030",
            "gameDesc": "Make your own custom keyboard art that everyone will love!\nDIY Keyboard 3D is an art game where you can use your creativity to become a keyboard designer and make your own custom keyboard!\nThere are various gameplay options to help you make a custom keyboard art masterpiece the way you like!\nChoose your favorite color or design to decorate each part of the keyboard art masterpiece.\nDIY keyboard 3D games will give you the easiest way to make your own keyboard and become the designer who creates the best custom keyboard ever!",
            "vidUrl": "https://youtu.be/WLOWEJTmB6c"
        },
        {
            "gameId": "1578",
            "gameType": "Action",
            "gameName": "Stealth Master 3D",
            "fileName": "StealthMaster3D",
            "gameLogo": "./webp/f3948fde82e24dd9b225ac255e54cb0e.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/c0b151817e2747319808e9cf1aa8ab49.webp",
            "gamePlayNumber": "102312",
            "gameDesc": "Sneak past enemies and strike with stealth in this crazy 3d ninja game! Each enemy has a vision cone ahead of them, stay out of it and sneak right up to their backside to strike. Each strike will earn you points. Master stealth and attacks and your ninja will surely top the leaderboard!",
            "vidUrl": "https://youtu.be/aOLS46tWGC4"
        },
        {
            "gameId": "2517",
            "gameType": "New,Action",
            "gameName": "Super Car",
            "fileName": "SuperCar",
            "gameLogo": "./webp/e335e7accb0c494693fb9375225fdc7b.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/4343ddc285234fd99e81862348e9f871.png",
            "gamePlayNumber": "100588",
            "gameDesc": "You have never played a race like this before!\nAny drawing will become a car!\nIf you are stuck draw another car until you pass the obstacle!",
            "vidUrl": "https://youtube.com/shorts/OSNTUsX-raE"
        },
        {
            "gameId": "2719",
            "gameType": "New,Action",
            "gameName": "Crowd Enhance",
            "fileName": "CrowdEnhance",
            "gameLogo": "./webp/e08cecf7e17f4769a211fd1db0089825.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/274fb1df3f7b47ed8d7ddf34abf5d6f1.png",
            "gamePlayNumber": "100055",
            "gameDesc": "You have to collect weapons and avoid obstacles on the platform tracks at all levels. Kill all the enemies and never let them get close to you.",
            "vidUrl": "https://youtube.com/shorts/CV0jGv7I8Qk"
        },
        {
            "gameId": "2505",
            "gameType": "Puzzle,New",
            "gameName": "Tasty Drop",
            "fileName": "TastyDrop",
            "gameLogo": "./webp/6a10ea08454541cf803fa08d3affaccb.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/601832711a744cd2bbc2157ab241f71d.png",
            "gamePlayNumber": "100105",
            "gameDesc": "You are just one step away from completing an awesome dish. All you have to do is drop the final element into the bowl. And Tasty Drop is all about that challenge. Experience the amazing physics system that provides the unique look and feel of the game. Solve exciting puzzles using experimentation and trial and error and, above all, have fun with the physics!",
            "vidUrl": "https://youtube.com/shorts/mGm5ogon-bw"
        },
        {
            "gameId": "2194",
            "gameType": "New,Action",
            "gameName": "Squad Alpha",
            "fileName": "SquadAlpha",
            "gameLogo": "./webp/f14fa3bb4dd9490691f6f7b076b73dca.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/8997fda9171846a1983988434025cc7e.png",
            "gamePlayNumber": "100050",
            "gameDesc": " Alpha Squad – Are you ready for the challenge?\nAre you looking for a fun casual shooter that is easy to play, yet has eye-catching action scenes and ? tactical challenges with real guns and live ammunition? Alpha Squad is a top-down shooter with highly intelligent mechanics, cool guns to upgrade, and addictive gameplay that will keep you wanting to press the trigger and figure out your strategy.\nBow, dodge, run, find cover, kill multiple targets, enjoy thrilling action scenes, complete endless levels, and earn exciting and rich rewards Use these rewards to upgrade your equipment and ?️ prove to the agents that you are the elite of the Alpha Squad!",
            "vidUrl": "https://youtu.be/BZFrbPzrwNY"
        },
        {
            "gameId": "2137",
            "gameType": "New,Action",
            "gameName": "Paw Care",
            "fileName": "PawCare",
            "gameLogo": "./webp/03ee6c7f43b04b1bb3f49bf2fd771f62.webp",
            "gameDetailsImg": "https://gamedesc.91onegame.com/eecc03bda53546c19bcaa5024172b0e8.png",
            "gamePlayNumber": "100117",
            "gameDesc": "Your beloved furry child needs care, love, and care. It's time to take them to the vet and do a physical examination. Do they always scratch the back of their ears? No problem, we can help you get rid of fleas. Do they always lick melon seeds? Maybe they stepped on something that had to be removed. This veterinarian can treat any disease that makes your pet uncomfortable.\nWhether you're a dog lover, a cat lover, or simply an animal lover, Pet Beauty Salon is a game for you. You can finally take care of your pet yourself. Brush their bristles, caress them, love them, all at your fingertips. Feel like a pet doctor. Come and run the clinic!",
            "vidUrl": "https://youtu.be/0zuar38ydLk"
        }
]